### ISSUE TITLE
bottom pressure instead of depth in grid_data.pressure.m

### ISSUE THREAD

**Issue by ShuwenTan-PO** [kkats/GO-SHIP-Easy-Ocean#9]
I found the horizontal interpolation by objective mapping (hinterp_bylon. and hinterp_bylat.m) requires bottom pressure at each station (maxp), however, lines 73-82 in grid_data.pressure.m seem to dump bottom depth to the code (deps(idxhere)). 

This should be easy to fix... e.g., replays lines 13-22 with 

% lat/lon and depth
stations = D_reported.Station;
nstn = length(stations);
[lats, lons, deps, pre_deps, tims] = deal(NaN(1, nstn));
for i = 1:nstn
    lats(i) = stations{i}.Lat;
    lons(i) = stations{i}.Lon;
    deps(i) = stations{i}.Depth;
    pre_deps(i) = gsw_p_from_z(-deps(i), lats(i));
    tims(i) = stations{i}.Time;
end

and replace deps with  pre_deps in lines 73-82.

Cheers!

**Comment by kkats** [comment]
Thank you for the feedback.

The `Depth` in `station` structure is actually bottom pressure in dbar.  It was not probably a good idea to calll pressure `Depth`. I have added a note at L.80 in README.md. The `Depth` conversion is performed at LL.133- in `reported_data.m`.  I appreciate your comment and thank you for using GO-SHIP EasyOcean.
